#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto3.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pruebas")]
	public partial class pruebaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertPRUEBAS_TA_01_CAT_USUARIOS(PRUEBAS_TA_01_CAT_USUARIOS instance);
    partial void UpdatePRUEBAS_TA_01_CAT_USUARIOS(PRUEBAS_TA_01_CAT_USUARIOS instance);
    partial void DeletePRUEBAS_TA_01_CAT_USUARIOS(PRUEBAS_TA_01_CAT_USUARIOS instance);
    partial void InsertPRUEBAS_TA_05_BITACORA(PRUEBAS_TA_05_BITACORA instance);
    partial void UpdatePRUEBAS_TA_05_BITACORA(PRUEBAS_TA_05_BITACORA instance);
    partial void DeletePRUEBAS_TA_05_BITACORA(PRUEBAS_TA_05_BITACORA instance);
    partial void InsertPRUEBAS_TA_02_CAT_CORPORACION(PRUEBAS_TA_02_CAT_CORPORACION instance);
    partial void UpdatePRUEBAS_TA_02_CAT_CORPORACION(PRUEBAS_TA_02_CAT_CORPORACION instance);
    partial void DeletePRUEBAS_TA_02_CAT_CORPORACION(PRUEBAS_TA_02_CAT_CORPORACION instance);
    partial void InsertPRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR(PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR instance);
    partial void UpdatePRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR(PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR instance);
    partial void DeletePRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR(PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR instance);
    partial void InsertPRUEBAS_TA_04_CAT_TAREAS(PRUEBAS_TA_04_CAT_TAREAS instance);
    partial void UpdatePRUEBAS_TA_04_CAT_TAREAS(PRUEBAS_TA_04_CAT_TAREAS instance);
    partial void DeletePRUEBAS_TA_04_CAT_TAREAS(PRUEBAS_TA_04_CAT_TAREAS instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    #endregion
		
		public pruebaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PruebasConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pruebaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PRUEBAS_TA_01_CAT_USUARIOS> PRUEBAS_TA_01_CAT_USUARIOS
		{
			get
			{
				return this.GetTable<PRUEBAS_TA_01_CAT_USUARIOS>();
			}
		}
		
		public System.Data.Linq.Table<PRUEBAS_TA_05_BITACORA> PRUEBAS_TA_05_BITACORA
		{
			get
			{
				return this.GetTable<PRUEBAS_TA_05_BITACORA>();
			}
		}
		
		public System.Data.Linq.Table<PRUEBAS_TA_02_CAT_CORPORACION> PRUEBAS_TA_02_CAT_CORPORACION
		{
			get
			{
				return this.GetTable<PRUEBAS_TA_02_CAT_CORPORACION>();
			}
		}
		
		public System.Data.Linq.Table<PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR> PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR
		{
			get
			{
				return this.GetTable<PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR>();
			}
		}
		
		public System.Data.Linq.Table<PRUEBAS_TA_04_CAT_TAREAS> PRUEBAS_TA_04_CAT_TAREAS
		{
			get
			{
				return this.GetTable<PRUEBAS_TA_04_CAT_TAREAS>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<UsersInRoles> UsersInRoles
		{
			get
			{
				return this.GetTable<UsersInRoles>();
			}
		}
		
		public System.Data.Linq.Table<View_Tarea_User> View_Tarea_User
		{
			get
			{
				return this.GetTable<View_Tarea_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRUEBAS_TA_01_CAT_USUARIOS")]
	public partial class PRUEBAS_TA_01_CAT_USUARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_ID;
		
		private string _T_NOMBRE;
		
		private string _T_APELLIDOS;
		
		private string _T_EMAIL;
		
		private System.Nullable<int> _T_Nivel_Usuaro;
		
		private string _T_Tipo_Usuario;
		
		private System.Nullable<int> _E_EDAD;
		
		private string _T_DIRECCION;
		
		private string _T_COLONIA;
		
		private System.Nullable<int> _REL_TA02_E_ID_CORPORACION;
		
		private string _T_PASSWORD;
		
		private string _T_USUARIO;
		
		private System.Nullable<int> _RoleID;
		
		private EntityRef<Roles> _Roles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(int value);
    partial void OnE_IDChanged();
    partial void OnT_NOMBREChanging(string value);
    partial void OnT_NOMBREChanged();
    partial void OnT_APELLIDOSChanging(string value);
    partial void OnT_APELLIDOSChanged();
    partial void OnT_EMAILChanging(string value);
    partial void OnT_EMAILChanged();
    partial void OnT_Nivel_UsuaroChanging(System.Nullable<int> value);
    partial void OnT_Nivel_UsuaroChanged();
    partial void OnT_Tipo_UsuarioChanging(string value);
    partial void OnT_Tipo_UsuarioChanged();
    partial void OnE_EDADChanging(System.Nullable<int> value);
    partial void OnE_EDADChanged();
    partial void OnT_DIRECCIONChanging(string value);
    partial void OnT_DIRECCIONChanged();
    partial void OnT_COLONIAChanging(string value);
    partial void OnT_COLONIAChanged();
    partial void OnREL_TA02_E_ID_CORPORACIONChanging(System.Nullable<int> value);
    partial void OnREL_TA02_E_ID_CORPORACIONChanged();
    partial void OnT_PASSWORDChanging(string value);
    partial void OnT_PASSWORDChanged();
    partial void OnT_USUARIOChanging(string value);
    partial void OnT_USUARIOChanged();
    partial void OnRoleIDChanging(System.Nullable<int> value);
    partial void OnRoleIDChanged();
    #endregion
		
		public PRUEBAS_TA_01_CAT_USUARIOS()
		{
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string T_NOMBRE
		{
			get
			{
				return this._T_NOMBRE;
			}
			set
			{
				if ((this._T_NOMBRE != value))
				{
					this.OnT_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._T_NOMBRE = value;
					this.SendPropertyChanged("T_NOMBRE");
					this.OnT_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_APELLIDOS", DbType="VarChar(86)")]
		public string T_APELLIDOS
		{
			get
			{
				return this._T_APELLIDOS;
			}
			set
			{
				if ((this._T_APELLIDOS != value))
				{
					this.OnT_APELLIDOSChanging(value);
					this.SendPropertyChanging();
					this._T_APELLIDOS = value;
					this.SendPropertyChanged("T_APELLIDOS");
					this.OnT_APELLIDOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_EMAIL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string T_EMAIL
		{
			get
			{
				return this._T_EMAIL;
			}
			set
			{
				if ((this._T_EMAIL != value))
				{
					this.OnT_EMAILChanging(value);
					this.SendPropertyChanging();
					this._T_EMAIL = value;
					this.SendPropertyChanged("T_EMAIL");
					this.OnT_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Nivel_Usuaro", DbType="Int")]
		public System.Nullable<int> T_Nivel_Usuaro
		{
			get
			{
				return this._T_Nivel_Usuaro;
			}
			set
			{
				if ((this._T_Nivel_Usuaro != value))
				{
					this.OnT_Nivel_UsuaroChanging(value);
					this.SendPropertyChanging();
					this._T_Nivel_Usuaro = value;
					this.SendPropertyChanged("T_Nivel_Usuaro");
					this.OnT_Nivel_UsuaroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_Tipo_Usuario", DbType="VarChar(20)")]
		public string T_Tipo_Usuario
		{
			get
			{
				return this._T_Tipo_Usuario;
			}
			set
			{
				if ((this._T_Tipo_Usuario != value))
				{
					this.OnT_Tipo_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._T_Tipo_Usuario = value;
					this.SendPropertyChanged("T_Tipo_Usuario");
					this.OnT_Tipo_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_EDAD", DbType="Int")]
		public System.Nullable<int> E_EDAD
		{
			get
			{
				return this._E_EDAD;
			}
			set
			{
				if ((this._E_EDAD != value))
				{
					this.OnE_EDADChanging(value);
					this.SendPropertyChanging();
					this._E_EDAD = value;
					this.SendPropertyChanged("E_EDAD");
					this.OnE_EDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_DIRECCION", DbType="VarChar(80)")]
		public string T_DIRECCION
		{
			get
			{
				return this._T_DIRECCION;
			}
			set
			{
				if ((this._T_DIRECCION != value))
				{
					this.OnT_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._T_DIRECCION = value;
					this.SendPropertyChanged("T_DIRECCION");
					this.OnT_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_COLONIA", DbType="VarChar(80)")]
		public string T_COLONIA
		{
			get
			{
				return this._T_COLONIA;
			}
			set
			{
				if ((this._T_COLONIA != value))
				{
					this.OnT_COLONIAChanging(value);
					this.SendPropertyChanging();
					this._T_COLONIA = value;
					this.SendPropertyChanged("T_COLONIA");
					this.OnT_COLONIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REL_TA02_E_ID_CORPORACION", DbType="Int")]
		public System.Nullable<int> REL_TA02_E_ID_CORPORACION
		{
			get
			{
				return this._REL_TA02_E_ID_CORPORACION;
			}
			set
			{
				if ((this._REL_TA02_E_ID_CORPORACION != value))
				{
					this.OnREL_TA02_E_ID_CORPORACIONChanging(value);
					this.SendPropertyChanging();
					this._REL_TA02_E_ID_CORPORACION = value;
					this.SendPropertyChanged("REL_TA02_E_ID_CORPORACION");
					this.OnREL_TA02_E_ID_CORPORACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PASSWORD", DbType="VarChar(50)")]
		public string T_PASSWORD
		{
			get
			{
				return this._T_PASSWORD;
			}
			set
			{
				if ((this._T_PASSWORD != value))
				{
					this.OnT_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._T_PASSWORD = value;
					this.SendPropertyChanged("T_PASSWORD");
					this.OnT_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_USUARIO", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string T_USUARIO
		{
			get
			{
				return this._T_USUARIO;
			}
			set
			{
				if ((this._T_USUARIO != value))
				{
					this.OnT_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._T_USUARIO = value;
					this.SendPropertyChanged("T_USUARIO");
					this.OnT_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int")]
		public System.Nullable<int> RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_PRUEBAS_TA_01_CAT_USUARIOS", Storage="_Roles", ThisKey="RoleID", OtherKey="RoleID", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.PRUEBAS_TA_01_CAT_USUARIOS.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.PRUEBAS_TA_01_CAT_USUARIOS.Add(this);
						this._RoleID = value.RoleID;
					}
					else
					{
						this._RoleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRUEBAS_TA_05_BITACORA")]
	public partial class PRUEBAS_TA_05_BITACORA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_ID;
		
		private string _T_CONTROLLER;
		
		private string _T_METHOD;
		
		private System.Nullable<int> _E_USER_ID;
		
		private string _T_MESSAGE;
		
		private System.Nullable<System.DateTime> _F_DATE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(int value);
    partial void OnE_IDChanged();
    partial void OnT_CONTROLLERChanging(string value);
    partial void OnT_CONTROLLERChanged();
    partial void OnT_METHODChanging(string value);
    partial void OnT_METHODChanged();
    partial void OnE_USER_IDChanging(System.Nullable<int> value);
    partial void OnE_USER_IDChanged();
    partial void OnT_MESSAGEChanging(string value);
    partial void OnT_MESSAGEChanged();
    partial void OnF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnF_DATEChanged();
    #endregion
		
		public PRUEBAS_TA_05_BITACORA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_CONTROLLER", DbType="VarChar(50)")]
		public string T_CONTROLLER
		{
			get
			{
				return this._T_CONTROLLER;
			}
			set
			{
				if ((this._T_CONTROLLER != value))
				{
					this.OnT_CONTROLLERChanging(value);
					this.SendPropertyChanging();
					this._T_CONTROLLER = value;
					this.SendPropertyChanged("T_CONTROLLER");
					this.OnT_CONTROLLERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_METHOD", DbType="VarChar(50)")]
		public string T_METHOD
		{
			get
			{
				return this._T_METHOD;
			}
			set
			{
				if ((this._T_METHOD != value))
				{
					this.OnT_METHODChanging(value);
					this.SendPropertyChanging();
					this._T_METHOD = value;
					this.SendPropertyChanged("T_METHOD");
					this.OnT_METHODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_USER_ID", DbType="Int")]
		public System.Nullable<int> E_USER_ID
		{
			get
			{
				return this._E_USER_ID;
			}
			set
			{
				if ((this._E_USER_ID != value))
				{
					this.OnE_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._E_USER_ID = value;
					this.SendPropertyChanged("E_USER_ID");
					this.OnE_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_MESSAGE", DbType="VarChar(200)")]
		public string T_MESSAGE
		{
			get
			{
				return this._T_MESSAGE;
			}
			set
			{
				if ((this._T_MESSAGE != value))
				{
					this.OnT_MESSAGEChanging(value);
					this.SendPropertyChanging();
					this._T_MESSAGE = value;
					this.SendPropertyChanged("T_MESSAGE");
					this.OnT_MESSAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_DATE
		{
			get
			{
				return this._F_DATE;
			}
			set
			{
				if ((this._F_DATE != value))
				{
					this.OnF_DATEChanging(value);
					this.SendPropertyChanging();
					this._F_DATE = value;
					this.SendPropertyChanged("F_DATE");
					this.OnF_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRUEBAS_TA_02_CAT_CORPORACION")]
	public partial class PRUEBAS_TA_02_CAT_CORPORACION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_ID;
		
		private string _T_CORPORACION;
		
		private string _T_DIRECCION;
		
		private string _T_DESCRIPCION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(int value);
    partial void OnE_IDChanged();
    partial void OnT_CORPORACIONChanging(string value);
    partial void OnT_CORPORACIONChanged();
    partial void OnT_DIRECCIONChanging(string value);
    partial void OnT_DIRECCIONChanged();
    partial void OnT_DESCRIPCIONChanging(string value);
    partial void OnT_DESCRIPCIONChanged();
    #endregion
		
		public PRUEBAS_TA_02_CAT_CORPORACION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_CORPORACION", DbType="VarChar(50)")]
		public string T_CORPORACION
		{
			get
			{
				return this._T_CORPORACION;
			}
			set
			{
				if ((this._T_CORPORACION != value))
				{
					this.OnT_CORPORACIONChanging(value);
					this.SendPropertyChanging();
					this._T_CORPORACION = value;
					this.SendPropertyChanged("T_CORPORACION");
					this.OnT_CORPORACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_DIRECCION", DbType="VarChar(50)")]
		public string T_DIRECCION
		{
			get
			{
				return this._T_DIRECCION;
			}
			set
			{
				if ((this._T_DIRECCION != value))
				{
					this.OnT_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._T_DIRECCION = value;
					this.SendPropertyChanged("T_DIRECCION");
					this.OnT_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_DESCRIPCION", DbType="VarChar(70)")]
		public string T_DESCRIPCION
		{
			get
			{
				return this._T_DESCRIPCION;
			}
			set
			{
				if ((this._T_DESCRIPCION != value))
				{
					this.OnT_DESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._T_DESCRIPCION = value;
					this.SendPropertyChanged("T_DESCRIPCION");
					this.OnT_DESCRIPCIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR")]
	public partial class PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_ID;
		
		private System.DateTime _FH_FECHAHORA_INICIAL;
		
		private System.DateTime _FH_FECHAHORA_FINAL;
		
		private System.Nullable<double> _FL_TIEMPO_PAUSAS;
		
		private System.Nullable<double> _FL_CAPACIDAD;
		
		private int _PRUEBAS_REL_T01_E_TRABAJADORES;
		
		private int _PRUEBAS_REL_T04_E_TAREA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(int value);
    partial void OnE_IDChanged();
    partial void OnFH_FECHAHORA_INICIALChanging(System.DateTime value);
    partial void OnFH_FECHAHORA_INICIALChanged();
    partial void OnFH_FECHAHORA_FINALChanging(System.DateTime value);
    partial void OnFH_FECHAHORA_FINALChanged();
    partial void OnFL_TIEMPO_PAUSASChanging(System.Nullable<double> value);
    partial void OnFL_TIEMPO_PAUSASChanged();
    partial void OnFL_CAPACIDADChanging(System.Nullable<double> value);
    partial void OnFL_CAPACIDADChanged();
    partial void OnPRUEBAS_REL_T01_E_TRABAJADORESChanging(int value);
    partial void OnPRUEBAS_REL_T01_E_TRABAJADORESChanged();
    partial void OnPRUEBAS_REL_T04_E_TAREAChanging(int value);
    partial void OnPRUEBAS_REL_T04_E_TAREAChanged();
    #endregion
		
		public PRUEBAS_TA_03_DISPONIBILIDAD_TRABAJADOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FH_FECHAHORA_INICIAL", DbType="DateTime NOT NULL")]
		public System.DateTime FH_FECHAHORA_INICIAL
		{
			get
			{
				return this._FH_FECHAHORA_INICIAL;
			}
			set
			{
				if ((this._FH_FECHAHORA_INICIAL != value))
				{
					this.OnFH_FECHAHORA_INICIALChanging(value);
					this.SendPropertyChanging();
					this._FH_FECHAHORA_INICIAL = value;
					this.SendPropertyChanged("FH_FECHAHORA_INICIAL");
					this.OnFH_FECHAHORA_INICIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FH_FECHAHORA_FINAL", DbType="DateTime NOT NULL")]
		public System.DateTime FH_FECHAHORA_FINAL
		{
			get
			{
				return this._FH_FECHAHORA_FINAL;
			}
			set
			{
				if ((this._FH_FECHAHORA_FINAL != value))
				{
					this.OnFH_FECHAHORA_FINALChanging(value);
					this.SendPropertyChanging();
					this._FH_FECHAHORA_FINAL = value;
					this.SendPropertyChanged("FH_FECHAHORA_FINAL");
					this.OnFH_FECHAHORA_FINALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_TIEMPO_PAUSAS", DbType="Float")]
		public System.Nullable<double> FL_TIEMPO_PAUSAS
		{
			get
			{
				return this._FL_TIEMPO_PAUSAS;
			}
			set
			{
				if ((this._FL_TIEMPO_PAUSAS != value))
				{
					this.OnFL_TIEMPO_PAUSASChanging(value);
					this.SendPropertyChanging();
					this._FL_TIEMPO_PAUSAS = value;
					this.SendPropertyChanged("FL_TIEMPO_PAUSAS");
					this.OnFL_TIEMPO_PAUSASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_CAPACIDAD", DbType="Float")]
		public System.Nullable<double> FL_CAPACIDAD
		{
			get
			{
				return this._FL_CAPACIDAD;
			}
			set
			{
				if ((this._FL_CAPACIDAD != value))
				{
					this.OnFL_CAPACIDADChanging(value);
					this.SendPropertyChanging();
					this._FL_CAPACIDAD = value;
					this.SendPropertyChanged("FL_CAPACIDAD");
					this.OnFL_CAPACIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRUEBAS_REL_T01_E_TRABAJADORES", DbType="Int NOT NULL")]
		public int PRUEBAS_REL_T01_E_TRABAJADORES
		{
			get
			{
				return this._PRUEBAS_REL_T01_E_TRABAJADORES;
			}
			set
			{
				if ((this._PRUEBAS_REL_T01_E_TRABAJADORES != value))
				{
					this.OnPRUEBAS_REL_T01_E_TRABAJADORESChanging(value);
					this.SendPropertyChanging();
					this._PRUEBAS_REL_T01_E_TRABAJADORES = value;
					this.SendPropertyChanged("PRUEBAS_REL_T01_E_TRABAJADORES");
					this.OnPRUEBAS_REL_T01_E_TRABAJADORESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRUEBAS_REL_T04_E_TAREA", DbType="Int NOT NULL")]
		public int PRUEBAS_REL_T04_E_TAREA
		{
			get
			{
				return this._PRUEBAS_REL_T04_E_TAREA;
			}
			set
			{
				if ((this._PRUEBAS_REL_T04_E_TAREA != value))
				{
					this.OnPRUEBAS_REL_T04_E_TAREAChanging(value);
					this.SendPropertyChanging();
					this._PRUEBAS_REL_T04_E_TAREA = value;
					this.SendPropertyChanged("PRUEBAS_REL_T04_E_TAREA");
					this.OnPRUEBAS_REL_T04_E_TAREAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRUEBAS_TA_04_CAT_TAREAS")]
	public partial class PRUEBAS_TA_04_CAT_TAREAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _E_ID;
		
		private string _T_NOMBRE;
		
		private string _T_DESCRIPCION;
		
		private int _E_PRIORIDAD;
		
		private System.Nullable<System.DateTime> _F_START;
		
		private System.Nullable<System.DateTime> _F_END;
		
		private int _PRUEBAS_TA_01_E_ID_USUARIOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnE_IDChanging(int value);
    partial void OnE_IDChanged();
    partial void OnT_NOMBREChanging(string value);
    partial void OnT_NOMBREChanged();
    partial void OnT_DESCRIPCIONChanging(string value);
    partial void OnT_DESCRIPCIONChanged();
    partial void OnE_PRIORIDADChanging(int value);
    partial void OnE_PRIORIDADChanged();
    partial void OnF_STARTChanging(System.Nullable<System.DateTime> value);
    partial void OnF_STARTChanged();
    partial void OnF_ENDChanging(System.Nullable<System.DateTime> value);
    partial void OnF_ENDChanged();
    partial void OnPRUEBAS_TA_01_E_ID_USUARIOSChanging(int value);
    partial void OnPRUEBAS_TA_01_E_ID_USUARIOSChanged();
    #endregion
		
		public PRUEBAS_TA_04_CAT_TAREAS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this.OnE_IDChanging(value);
					this.SendPropertyChanging();
					this._E_ID = value;
					this.SendPropertyChanged("E_ID");
					this.OnE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string T_NOMBRE
		{
			get
			{
				return this._T_NOMBRE;
			}
			set
			{
				if ((this._T_NOMBRE != value))
				{
					this.OnT_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._T_NOMBRE = value;
					this.SendPropertyChanged("T_NOMBRE");
					this.OnT_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_DESCRIPCION", DbType="VarChar(100)")]
		public string T_DESCRIPCION
		{
			get
			{
				return this._T_DESCRIPCION;
			}
			set
			{
				if ((this._T_DESCRIPCION != value))
				{
					this.OnT_DESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._T_DESCRIPCION = value;
					this.SendPropertyChanged("T_DESCRIPCION");
					this.OnT_DESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_PRIORIDAD", DbType="Int NOT NULL")]
		public int E_PRIORIDAD
		{
			get
			{
				return this._E_PRIORIDAD;
			}
			set
			{
				if ((this._E_PRIORIDAD != value))
				{
					this.OnE_PRIORIDADChanging(value);
					this.SendPropertyChanging();
					this._E_PRIORIDAD = value;
					this.SendPropertyChanged("E_PRIORIDAD");
					this.OnE_PRIORIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_START", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_START
		{
			get
			{
				return this._F_START;
			}
			set
			{
				if ((this._F_START != value))
				{
					this.OnF_STARTChanging(value);
					this.SendPropertyChanging();
					this._F_START = value;
					this.SendPropertyChanged("F_START");
					this.OnF_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_END", DbType="DateTime")]
		public System.Nullable<System.DateTime> F_END
		{
			get
			{
				return this._F_END;
			}
			set
			{
				if ((this._F_END != value))
				{
					this.OnF_ENDChanging(value);
					this.SendPropertyChanging();
					this._F_END = value;
					this.SendPropertyChanged("F_END");
					this.OnF_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRUEBAS_TA_01_E_ID_USUARIOS", DbType="Int NOT NULL")]
		public int PRUEBAS_TA_01_E_ID_USUARIOS
		{
			get
			{
				return this._PRUEBAS_TA_01_E_ID_USUARIOS;
			}
			set
			{
				if ((this._PRUEBAS_TA_01_E_ID_USUARIOS != value))
				{
					this.OnPRUEBAS_TA_01_E_ID_USUARIOSChanging(value);
					this.SendPropertyChanging();
					this._PRUEBAS_TA_01_E_ID_USUARIOS = value;
					this.SendPropertyChanged("PRUEBAS_TA_01_E_ID_USUARIOS");
					this.OnPRUEBAS_TA_01_E_ID_USUARIOSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _RoleName;
		
		private EntitySet<PRUEBAS_TA_01_CAT_USUARIOS> _PRUEBAS_TA_01_CAT_USUARIOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public Roles()
		{
			this._PRUEBAS_TA_01_CAT_USUARIOS = new EntitySet<PRUEBAS_TA_01_CAT_USUARIOS>(new Action<PRUEBAS_TA_01_CAT_USUARIOS>(this.attach_PRUEBAS_TA_01_CAT_USUARIOS), new Action<PRUEBAS_TA_01_CAT_USUARIOS>(this.detach_PRUEBAS_TA_01_CAT_USUARIOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_PRUEBAS_TA_01_CAT_USUARIOS", Storage="_PRUEBAS_TA_01_CAT_USUARIOS", ThisKey="RoleID", OtherKey="RoleID")]
		public EntitySet<PRUEBAS_TA_01_CAT_USUARIOS> PRUEBAS_TA_01_CAT_USUARIOS
		{
			get
			{
				return this._PRUEBAS_TA_01_CAT_USUARIOS;
			}
			set
			{
				this._PRUEBAS_TA_01_CAT_USUARIOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRUEBAS_TA_01_CAT_USUARIOS(PRUEBAS_TA_01_CAT_USUARIOS entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_PRUEBAS_TA_01_CAT_USUARIOS(PRUEBAS_TA_01_CAT_USUARIOS entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsersInRoles")]
	public partial class UsersInRoles
	{
		
		private System.Nullable<int> _RoleID;
		
		private System.Nullable<int> _E_ID;
		
		public UsersInRoles()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int")]
		public System.Nullable<int> RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_ID", DbType="Int")]
		public System.Nullable<int> E_ID
		{
			get
			{
				return this._E_ID;
			}
			set
			{
				if ((this._E_ID != value))
				{
					this._E_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Tarea_User")]
	public partial class View_Tarea_User
	{
		
		private string _T_NOMBRE;
		
		private System.Nullable<int> _Cantidad;
		
		public View_Tarea_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string T_NOMBRE
		{
			get
			{
				return this._T_NOMBRE;
			}
			set
			{
				if ((this._T_NOMBRE != value))
				{
					this._T_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
